services:
  python-ssh-runtime:
    profiles: ["python-ssh"]
    build:
      context: .
      dockerfile: runtime/python-ssh.Dockerfile
      args:
        SSH_USERNAME: ${USERNAME}
        SSH_PASSWORD: ${PASSWORD}
    image: python-execution-runtime
    ports:
      - "${PORT}:22"

  jupyter-notebook-runtime:
    profiles: ["jupyter-notebook"]
    image: jupyter/scipy-notebook:python-3.10
    ports:
      - "${PORT}:8888"
    command: ["start-notebook.sh", "--NotebookApp.token='${TOKEN}'"]

  apache-zeppelin-runtime:
    profiles: ["apache-zeppelin"]
    build:
      context: .
      dockerfile: runtime/apache-zeppelin.Dockerfile
    ports:
      - "${PORT}:8080"
