services:
  core:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: automated-tabular-data-analysis
    ports:
      - "${PORT}:8501"
    env_file:
      - .env
      
  python-ssh-runtime:
    profiles: ["python-ssh"]
    build:
      context: .
      dockerfile: runtime/python-ssh.Dockerfile
      args:
        SSH_USERNAME: ${USERNAME}
        SSH_PASSWORD: ${PASSWORD}
    image: python-execution-runtime
    ports:
      - "${RUNTIME_PORT}:22"

  jupyter-notebook-runtime:
    profiles: ["jupyter-notebook"]
    build:
      context: .
      dockerfile: runtime/jupyter-notebook.Dockerfile
    ports:
      - "${RUNTIME_PORT}:8888"
    environment:
      - TOKEN=${TOKEN}

  apache-zeppelin-runtime:
    profiles: ["apache-zeppelin"]
    build:
      context: .
      dockerfile: runtime/apache-zeppelin.Dockerfile
    ports:
      - "${RUNTIME_PORT}:8080"
