version: "3.8"

services:
  execution-runtime:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_USERNAME: ${SSH_USERNAME}
        SSH_PASSWORD: ${SSH_PASSWORD}
    image: python-execution-runtime
    ports:
      - "${SSH_PORT}:22"