name: Build, Push and Deploy Docker Image of Notebook Runtime

on:
  push:
    branches: master
    paths: 'runtime/jupyter-notebook.Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
            docker build -t ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.NOTEBOOK_TAG }}:${{ github.sha }} .
            docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.NOTEBOOK_TAG }}:${{ github.sha }}

      - name: Deploy to Azure Container App
        run: |
            az containerapp update \
              --name ${{ vars.NOTEBOOK_CONTAINER_NAME }} \
              --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
              --image ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.NOTEBOOK_TAG }}:${{ github.sha }} \
        